
class Stream
{
    [description("optional - present if stream is associated with command otherwise associated with shell")]
    string commandId;

    string streamName;
    string data;
    uint32 dataLength;
    boolean endOfStream;
};

class CommandState
{
    [description("optional")]
    string commandId;

    [description(
        "http://schemas.microsoft.com/wbem/wsman/1/windows/shell/CommandState/Done,
         http://schemas.microsoft.com/wbem/wsman/1/windows/shell/CommandState/Pending,
         http://schemas.microsoft.com/wbem/wsman/1/windows/shell/CommandState/Running")]
    string state;

    [description("process exit code")]
    uint32 exitCode;
};

class EnvironmentVariable
{
    string Name;
    string Value;
};


class Shell
{
    string Name;
    [key] string ShellId;
    string WorkingDirectory;
    [embeddedinstance("EnvironmentVariable")] string Environment[];
    string InputStreams; /* space delimited string */
    string OutputStreams; /* space delimited string */
    string CompressionMode;
    string ResourceUri;
    string Owner;
    string Locale;
    string DataLocale;
    string CreationXml;

    Uint32 Command(
        string command,
        string arguments[],
        [out] string CommandId
        );

    Uint32 Send(
        [embeddedinstance("Stream")] string streamData
        );

    Uint32 Receive(
        string commandId,
        string streamSet,
        [out, embeddedinstance("Stream")] string Stream ,
        [out, embeddedinstance("CommandState")] string CommandState
        );

    Uint32 Signal(
        string commandId,

        [description(
            "http://schemas.microsoft.com/wbem/wsman/1/windows/shell/signal/Terminate,
            http://schemas.microsoft.com/wbem/wsman/1/windows/shell/signal/Break,
            http://schemas.microsoft.com/wbem/wsman/1/windows/shell/signal/Pause,
            http://schemas.microsoft.com/wbem/wsman/1/windows/shell/signal/Resume,
            http://schemas.microsoft.com/wbem/wsman/1/windows/shell/signal/Exit")]
        string code
        );

    [static]
    Uint32 Connect(
        string shellId,
        string commandId,
        string inboundConnectionInfo
        );

};

class Command
{
    [key] string ShellId;
    [key] string CommandId;
};
